-- Generated by scripts/ci/dump_platform_sql.mjs from the live project.
-- Do not edit by hand: regenerate, and review the diff like the baseline's.
--
-- What the app needs outside the `public` schema, which the baseline does not
-- contain: the trigger that creates profiles, the storage buckets and the
-- storage policies. Apply after 00000000000000_baseline.sql. Idempotent.

BEGIN;

-- Profiles are created by this trigger on every new auth user.
DROP TRIGGER IF EXISTS "on_auth_user_created" ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Storage buckets.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('avatars', 'avatars', true, 15728640, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif', 'image/heic', 'image/heif']::text[])
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit, allowed_mime_types = EXCLUDED.allowed_mime_types;
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('boutique', 'boutique', true, 15728640, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif', 'image/heic', 'image/heif']::text[])
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit, allowed_mime_types = EXCLUDED.allowed_mime_types;
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('studio-wardrobe', 'studio-wardrobe', false, 15728640, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif', 'image/heic', 'image/heif']::text[])
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit, allowed_mime_types = EXCLUDED.allowed_mime_types;
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('vault-assets', 'vault-assets', true, 15728640, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif', 'image/heic', 'image/heif', 'application/pdf', 'application/zip', 'application/x-zip-compressed']::text[])
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit, allowed_mime_types = EXCLUDED.allowed_mime_types;
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('vault-resources', 'vault-resources', false, 15728640, ARRAY['application/pdf', 'application/zip', 'application/x-zip-compressed', 'image/jpeg', 'image/png', 'image/webp']::text[])
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit, allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Storage policies.
DROP POLICY IF EXISTS "Admin All Access" ON storage.objects;
CREATE POLICY "Admin All Access" ON storage.objects
    AS PERMISSIVE
    FOR ALL
    TO public
    USING (((bucket_id = 'boutique'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))))))
    WITH CHECK (((bucket_id = 'boutique'::text) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text))))));
DROP POLICY IF EXISTS "Admins can upload assets" ON storage.objects;
CREATE POLICY "Admins can upload assets" ON storage.objects
    AS PERMISSIVE
    FOR INSERT
    TO "authenticated"
    WITH CHECK (((bucket_id = 'vault-assets'::text) AND (public.get_user_role(( SELECT auth.uid() AS uid)) = 'admin'::text)));
DROP POLICY IF EXISTS "Admins can upload resources" ON storage.objects;
CREATE POLICY "Admins can upload resources" ON storage.objects
    AS PERMISSIVE
    FOR INSERT
    TO "authenticated"
    WITH CHECK (((bucket_id = 'vault-resources'::text) AND (public.get_user_role(( SELECT auth.uid() AS uid)) = 'admin'::text)));
DROP POLICY IF EXISTS "Avatar images are publicly accessible." ON storage.objects;
CREATE POLICY "Avatar images are publicly accessible." ON storage.objects
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((bucket_id = 'avatars'::text));
DROP POLICY IF EXISTS "Avatar owners can upload" ON storage.objects;
CREATE POLICY "Avatar owners can upload" ON storage.objects
    AS PERMISSIVE
    FOR INSERT
    TO "authenticated"
    WITH CHECK (((bucket_id = 'avatars'::text) AND (split_part(name, '/'::text, 1) = (( SELECT auth.uid() AS uid))::text)));
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((bucket_id = 'boutique'::text));
DROP POLICY IF EXISTS "studio_wardrobe_owner_delete" ON storage.objects;
CREATE POLICY "studio_wardrobe_owner_delete" ON storage.objects
    AS PERMISSIVE
    FOR DELETE
    TO "authenticated"
    USING (((bucket_id = 'studio-wardrobe'::text) AND public.can_access_wardrobe_object(name)));
DROP POLICY IF EXISTS "studio_wardrobe_owner_insert" ON storage.objects;
CREATE POLICY "studio_wardrobe_owner_insert" ON storage.objects
    AS PERMISSIVE
    FOR INSERT
    TO "authenticated"
    WITH CHECK (((bucket_id = 'studio-wardrobe'::text) AND public.can_access_wardrobe_object(name)));
DROP POLICY IF EXISTS "studio_wardrobe_owner_read" ON storage.objects;
CREATE POLICY "studio_wardrobe_owner_read" ON storage.objects
    AS PERMISSIVE
    FOR SELECT
    TO "authenticated"
    USING (((bucket_id = 'studio-wardrobe'::text) AND public.can_access_wardrobe_object(name)));
DROP POLICY IF EXISTS "studio_wardrobe_owner_update" ON storage.objects;
CREATE POLICY "studio_wardrobe_owner_update" ON storage.objects
    AS PERMISSIVE
    FOR UPDATE
    TO "authenticated"
    USING (((bucket_id = 'studio-wardrobe'::text) AND public.can_access_wardrobe_object(name)));

COMMIT;
