#!/usr/bin/env node
/**
 * Write supabase/platform.sql: the objects the app depends on that live
 * OUTSIDE the `public` schema, and so are not in the baseline dump.
 *
 *   node scripts/ci/dump_platform_sql.mjs           # regenerate the file
 *   node scripts/ci/dump_platform_sql.mjs --check   # exit 1 if it has drifted
 *
 * Found 2026-09-28 while building a database for the browser tests in CI:
 * the baseline (`pg_dump --schema=public`) leaves out
 *   - the `on_auth_user_created` trigger on auth.users, which creates every
 *     profile (without it a signup has no profile, so no role, no access);
 *   - the storage buckets (which exist, which are private, size and type limits);
 *   - the storage policies (who may read and write which files).
 * A database built from the baseline alone has none of them. That matters for
 * CI, and for disaster recovery into a fresh project ("Scenario 3" in
 * docs/DISASTER-RECOVERY.md), where these were otherwise recreated by hand.
 *
 * Read-only: one transaction with default_transaction_read_only. Policy
 * expressions are rendered with an empty search_path so every name comes out
 * schema-qualified and the file replays anywhere.
 */
import { Client } from 'pg';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
dotenv.config({ path: path.join(root, '.env.local') });
const OUT = path.join(root, 'supabase/platform.sql');
const checkOnly = process.argv.includes('--check');

if (!process.env.DATABASE_URL) {
    console.error('DATABASE_URL is missing (.env.local).');
    process.exit(2);
}

const lit = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const ident = (v) => `"${String(v).replace(/"/g, '""')}"`;

const client = new Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
await client.connect();
let sql;
try {
    await client.query('BEGIN READ ONLY');
    await client.query("SET LOCAL search_path = ''");

    const { rows: triggers } = await client.query(`
        SELECT t.tgname, pg_get_triggerdef(t.oid) AS def
        FROM pg_trigger t
        WHERE t.tgrelid = 'auth.users'::regclass AND NOT t.tgisinternal
        ORDER BY t.tgname`);

    const { rows: buckets } = await client.query(`
        SELECT id, name, public, file_size_limit, allowed_mime_types
        FROM storage.buckets ORDER BY id`);

    const { rows: policies } = await client.query(`
        SELECT p.polname AS name,
               CASE p.polcmd WHEN 'r' THEN 'SELECT' WHEN 'a' THEN 'INSERT' WHEN 'w' THEN 'UPDATE'
                             WHEN 'd' THEN 'DELETE' ELSE 'ALL' END AS cmd,
               p.polpermissive AS permissive,
               ARRAY(SELECT CASE WHEN r = 0 THEN 'public' ELSE pg_get_userbyid(r) END
                     FROM unnest(p.polroles) AS r ORDER BY 1)::text[] AS roles,
               pg_get_expr(p.polqual, p.polrelid) AS qual,
               pg_get_expr(p.polwithcheck, p.polrelid) AS with_check
        FROM pg_policy p
        WHERE p.polrelid = 'storage.objects'::regclass
        ORDER BY p.polname`);
    await client.query('ROLLBACK');

    const out = [];
    out.push(`-- Generated by scripts/ci/dump_platform_sql.mjs from the live project.
-- Do not edit by hand: regenerate, and review the diff like the baseline's.
--
-- What the app needs outside the \`public\` schema, which the baseline does not
-- contain: the trigger that creates profiles, the storage buckets and the
-- storage policies. Apply after 00000000000000_baseline.sql. Idempotent.

BEGIN;
`);
    out.push('-- Profiles are created by this trigger on every new auth user.');
    for (const t of triggers) {
        out.push(`DROP TRIGGER IF EXISTS ${ident(t.tgname)} ON auth.users;`);
        out.push(`${t.def};`);
    }
    out.push('\n-- Storage buckets.');
    for (const b of buckets) {
        const mimes = b.allowed_mime_types ? `ARRAY[${b.allowed_mime_types.map(lit).join(', ')}]::text[]` : 'NULL';
        out.push(`INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (${lit(b.id)}, ${lit(b.name)}, ${b.public}, ${b.file_size_limit ?? 'NULL'}, ${mimes})
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit, allowed_mime_types = EXCLUDED.allowed_mime_types;`);
    }
    out.push('\n-- Storage policies.');
    for (const p of policies) {
        out.push(`DROP POLICY IF EXISTS ${ident(p.name)} ON storage.objects;`);
        const parts = [`CREATE POLICY ${ident(p.name)} ON storage.objects`, `AS ${p.permissive ? 'PERMISSIVE' : 'RESTRICTIVE'}`,
            `FOR ${p.cmd}`, `TO ${p.roles.map((r) => (r === 'public' ? 'public' : ident(r))).join(', ')}`];
        if (p.qual) parts.push(`USING (${p.qual})`);
        if (p.with_check) parts.push(`WITH CHECK (${p.with_check})`);
        out.push(`${parts.join('\n    ')};`);
    }
    out.push('\nCOMMIT;\n');
    sql = out.join('\n');
} finally {
    await client.end();
}

if (checkOnly) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : '';
    if (current !== sql) {
        console.error('supabase/platform.sql does not match the live project. Run: node scripts/ci/dump_platform_sql.mjs');
        process.exit(1);
    }
    console.log('supabase/platform.sql matches the live project. No drift.');
} else {
    fs.writeFileSync(OUT, sql);
    console.log(`Wrote ${path.relative(root, OUT)}: ${sql.split('\n').length} lines.`);
}
