import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

/**
 * Real PostgreSQL, in process, loaded from the schema the live database
 * actually has.
 *
 * `supabase/migrations/00000000000000_baseline.sql` is a `pg_dump` of the live
 * schema, regenerated by scripts/backup/regenerate_baseline.mjs. Loading it
 * whole — rather than hand-copying the tables a test needs — is the point: a
 * hand-copied slice is the test author's belief about the schema, and a test
 * run against a belief can only ever agree with it. This way RLS policies,
 * grants, CHECK constraints, FKs and function bodies are the ones in
 * production.
 *
 * Only what Supabase provides OUTSIDE the dump is stubbed here: the three API
 * roles, `auth.uid()`/`auth.role()`/`auth.users`, and the storage schema.
 * `auth.uid()` reads the same `request.jwt.claim.sub` setting PostgREST sets.
 */
const SUPABASE_PRELUDE = `
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN BYPASSRLS;
-- Owns default privileges in the dump; never used by a test.
CREATE ROLE supabase_admin NOLOGIN;
DROP SCHEMA public CASCADE;
CREATE SCHEMA auth;
CREATE SCHEMA storage;
GRANT USAGE ON SCHEMA auth, storage TO anon, authenticated, service_role;
CREATE TABLE auth.users (id uuid PRIMARY KEY, email text);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$ SELECT current_user::text $$;
CREATE TABLE storage.buckets (id text PRIMARY KEY, public boolean, file_size_limit bigint, allowed_mime_types text[]);
CREATE TABLE storage.objects (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, bucket_id text, name text);
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
GRANT ALL ON ALL TABLES IN SCHEMA storage TO anon, authenticated, service_role;
-- Supabase's own definition: every path segment but the last.
CREATE FUNCTION storage.foldername(name text) RETURNS text[] LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE _parts text[];
BEGIN
    SELECT string_to_array(name, '/') INTO _parts;
    RETURN _parts[1:array_length(_parts, 1) - 1];
END $$;
`;

/** The dump minus psql meta-commands (`\\restrict`), which are not SQL. */
function baselineSql(): string {
    return readFileSync('supabase/migrations/00000000000000_baseline.sql', 'utf8')
        .split('\n')
        .filter(line => !line.startsWith('\\'))
        .join('\n');
}

export async function createLiveSchemaDb(): Promise<PGlite> {
    const db = new PGlite();
    await db.exec(SUPABASE_PRELUDE);
    await db.exec(baselineSql());
    // The dump configures its own session: search_path '' and, critically,
    // row_security = off. Left in place, a query RLS would filter instead
    // fails with 42501 — the same code a real permission denial returns — so
    // a "denied" assertion would pass for the wrong reason. Undo all of it.
    await db.exec('RESET ALL');
    const { rows } = await db.query<{ row_security: string }>('SHOW row_security');
    if (rows[0].row_security !== 'on') throw new Error('row_security is not on; RLS tests would be meaningless');
    return db;
}

export function readMigration(name: string): string {
    return readFileSync(`supabase/migrations/${name}`, 'utf8');
}

export type ApiRole = 'anon' | 'authenticated' | 'service_role';

/**
 * Run `sql` exactly as PostgREST would for this caller, then throw it away.
 *
 * Always rolled back, so tests cannot leak state into each other through a
 * write that happened to succeed.
 */
export async function asRole<T = Record<string, unknown>>(
    db: PGlite,
    role: ApiRole,
    userId: string | null,
    sql: string,
    params: unknown[] = []
) {
    await db.exec('BEGIN');
    try {
        await db.exec(`SET LOCAL ROLE ${role}`);
        await db.query("SELECT set_config('request.jwt.claim.sub', $1, true)", [userId ?? '']);
        return await db.query<T>(sql, params);
    } finally {
        await db.exec('ROLLBACK');
    }
}

/** A user as Supabase has one: an auth.users row and its profile. */
export async function createUser(
    db: PGlite,
    id: string,
    profile: Record<string, unknown> = {}
): Promise<void> {
    await db.query('INSERT INTO auth.users (id, email) VALUES ($1, $2)', [id, `${id.slice(-4)}@example.invalid`]);
    const columns = ['id', ...Object.keys(profile)];
    const values = [id, ...Object.values(profile)];
    const placeholders = values.map((_, i) => `$${i + 1}`).join(', ');
    await db.query(`INSERT INTO public.profiles (${columns.join(', ')}) VALUES (${placeholders})`, values);
}
